//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyCUSX.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyCUSX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EasyCUSX]
        ///Encoding=1
        ///PBVersion=1
        ///Type=5
        ///AutoLogon=0
        ///UseRasCredentials=0
        ///LowDateTime=-1442570256
        ///HighDateTime=30421260
        ///DialParamsUID=3935562
        ///Guid=542A2C39BFF88C42B1739456BB012D60
        ///VpnStrategy=0
        ///ExcludedProtocols=0
        ///LcpExtensions=1
        ///DataEncryption=8
        ///SwCompression=0
        ///NegotiateMultilinkAlways=0
        ///SkipDoubleDialDialog=0
        ///DialMode=0
        ///OverridePref=15
        ///RedialAttempts=3
        ///RedialSeconds=60
        ///IdleDisconnectSeconds=0
        ///RedialOnLinkFailure=1
        ///CallbackMode=0
        ///CustomDialDll=
        ///CustomDialFunc=
        ///CustomRasDialDll=
        ///Fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pbk_ChinaDNS {
            get {
                return ResourceManager.GetString("pbk_ChinaDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EasyCUSX]
        ///Encoding=1
        ///PBVersion=1
        ///Type=5
        ///AutoLogon=0
        ///UseRasCredentials=0
        ///LowDateTime=155271632
        ///HighDateTime=30421258
        ///DialParamsUID=3935562
        ///Guid=542A2C39BFF88C42B1739456BB012D60
        ///VpnStrategy=0
        ///ExcludedProtocols=0
        ///LcpExtensions=1
        ///DataEncryption=8
        ///SwCompression=0
        ///NegotiateMultilinkAlways=0
        ///SkipDoubleDialDialog=0
        ///DialMode=0
        ///OverridePref=15
        ///RedialAttempts=3
        ///RedialSeconds=60
        ///IdleDisconnectSeconds=0
        ///RedialOnLinkFailure=1
        ///CallbackMode=0
        ///CustomDialDll=
        ///CustomDialFunc=
        ///CustomRasDialDll=
        ///Forc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pbk_normal {
            get {
                return ResourceManager.GetString("pbk_normal", resourceCulture);
            }
        }
    }
}
